#
# Marcio Ribeiro <binary@b1n.org>
#

PDFLATEX ?= /usr/bin/pdflatex

all:
	$(PDFLATEX) $(FILE).tex

clean:
	rm -f $(FILE).aux $(FILE).log $(FILE).out $(FILE).pdf $(FILE).snm $(FILE).toc $(FILE).nav $(FILE).vrb texput.log
